### ISSUE TITLE
Bugs with Alluminum Alloy Ingots and Tank

### ISSUE THREAD

**Issue by DatrixTHLK** [MightyCupcakes/ArmourReborn#2]
1. http://tinypic.com/r/rk0z80/9 <--- Having trouble re-smelting the ingots Alumin(i)um Alloy in the furnace 1.0.16 forge 12.18.1.2094

**Comment by DatrixTHLK** [comment]
Still having an issue with lava. The first bucket is placed into the forge furnace the second bucket goes in but disappears as soon as I put any ingot/ore in it. 1.0-18. I'm not sure as to what to send you, whether it be video proof of it, or the fml log. If it isn't your mod, then I can bear with it.

**Comment by MightyCupcakes** [comment]
I can't reproduce it on my side. If you haven't already, make sure you break all the furnance blocks and place them into the world again after updating.

**Comment by DatrixTHLK** [comment]
Ok. I will try that then and see what happens. Thanks
